### ISSUE TITLE
When i try to edit an image like sayori's Head in adobe animate,i cannot edit it

### ISSUE THREAD

**Issue by YandereNico** [Jorge-SunSpirit/Doki-Doki-Takeover#11]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## Please describe your issue. Provide extensive detail and images if possible.
[](url)
![image](https://user-images.githubusercontent.com/77053181/156420123-9e5dd19b-1680-4494-bd3e-e55e34c23984.png)

**Comment by ActualMandM** [comment]
double-click > update
