### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by WlloX** [Jorge-SunSpirit/Doki-Doki-Takeover#13]
when i try to complile it it says:
source/Main.hx:3: characters 8-16 : Type not found : Gamejolt
source/GameJolt.hx:110: characters 22-28 : Type name GameJoltAPI is redefined from module GameJolt
source/GameJolt.hx:110: characters 22-28 : For function argument 'x'
source/GameJolt.hx:318: characters 67-73 : Module GJKeys does not define type GJKeys
source/GameJolt.hx:318: characters 67-73 : For optional function argument 'Text'

**Comment by ActualMandM** [comment]
remove `FEATURE_GAMEJOLT` in Project.xml

**Comment by WlloX** [comment]
ty

**Comment by WlloX** [comment]
Now its saying "source/Main.hx:3: characters 8-16 : Module GameJolt does not define type GameJolt"

> remove `FEATURE_GAMEJOLT` in Project.xml
