### ISSUE TITLE
Bug Report: When I make a project with the HTML files it just is stuck at the loading screen.

### ISSUE THREAD

**Issue by EpicLifeDog** [Jorge-SunSpirit/Doki-Doki-Takeover#16]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by ActualMandM** [comment]
What percentage is it stuck at?

**Comment by EpicLifeDog** [comment]
> What percentage is it stuck at? I know the GameJolt version ends up getting stuck at either 0% or 3%. Haven't been able to figure it out yet.

0%
![image](https://user-images.githubusercontent.com/105741808/178378485-883aed09-4686-4db0-9297-a7d3ffc7d643.png)

**Comment by TheRealJake12** [comment]
its a KE bug. it has to do with Fullscreen keybinds and whatnot. Just go through every state and remove every instance of fullscreen and volUp and volDown binds

**Comment by EpicLifeDog** [comment]
> its a KE bug. it has to do with Fullscreen keybinds and whatnot. Just go through every state and remove every instance of fullscreen and volUp and volDown binds

K thx

**Comment by ActualMandM** [comment]
aren't the fullscren/volUp/volDown stuff from a much later version of KE? iirc, DDTO was based off 1.4.2

**Comment by TheRealJake12** [comment]
at one point wasnt it on 1.8?

**Comment by TheRealJake12** [comment]
ig not

**Comment by ActualMandM** [comment]
With DDTO+, we've decided that we'll no longer be supporting HTML5. Since it's coming out in a week, I'll be closing this issue. Sorry for the inconvenience.
