### ISSUE TITLE
Linux Execution Issues

### ISSUE THREAD

**Issue by EndEmpire** [Jorge-SunSpirit/Doki-Doki-Takeover#17]
Hello! I'll preface this by saying I'm still somewhat new to Linux so my apologies if the answer to this is obvious.
I've been able to launch the Linux version of DDTO if I'm in the directory containing the [DokiTakeover] executable by using [./DokiTakeover].

However, if I try to run it from any other directory like in these examples:
While in assets: `../DokiTakeover`
While in the directory above [Doki.Doki.Takeover.Linux]: `/Doki.Doki.Takeover.Linux/DokiTakeover`

I get the error: 
Error : Could not load module lime@lime_application_create__prime

I'd imagine this probably has more to do with the Haxe Engine then your mod in specific and I can still run the mod, but I nest directories to organize files so it's a bit of a pain to navigate to that folder every time instead of using a .desktop file.
If anyone has any advice that would be appreciated. Thanks!

I'm running:
Linux Mint 20.3 x86_64
bash 5.0.17

**Comment by ActualMandM** [comment]
The game's assets are stored inside the asset folder, so when the executable is moved elsewhere it'll try looking for an assets folder in its directory with no luck.

I'm pretty sure you can make a .desktop file that points to the path of the executable.

**Comment by EndEmpire** [comment]
Seems as though I was misunderstood. I will try to provide clarification. 

**I did not rearrange or remove any files after extracting [Doki.Doki.Takeover.Linux.tar.gz].**

When I typed:
============================================================================
However, if I try to run it from any other directory like in these examples:
While in assets: `../DokiTakeover`
While in the directory above [Doki.Doki.Takeover.Linux]: `/Doki.Doki.Takeover.Linux/DokiTakeover`
============================================================================

I was not trying to say that I moved the [DokiTakeover] executable to the [assets] directory or anywhere else, but instead that I navigated to the [assets] directory in the terminal and then used the bash shortcut ".." to look in the directory above [assets] and execute [DokiTakeover]. The purpose of this was to try to executing [DokiTakeover] outside of its directory and instead providing a file path there.

My apologies for the confusion. (It's also entirely possible I misunderstood what you typed as well to which case I am sorry for the trouble!)


I have done further testing with a newly downloaded and extracted copy of [Doki.Doki.Takeover.Linux.tar.gz].
The testing and results are as follows:

A new copy of [Doki.Doki.Takeover.Linux.tar.gz] is downloaded to /home/(user)/doki

[Doki.Doki.Takeover.Linux.tar.gz] is extracted in /home/(user)/doki

I run navigate to /home/(user)/doki/Doki.Doki.Takeover.Linux in a terminal and run `sudo chmod 777 DokiTakeover`

DokiTakeover is set to [Allow executing file as program]

Double clicking the program displays an error for [Unknown file type]

Navigating to /home/(user)/doki/Doki.Doki.Takeover.Linux in the terminal and running `./DokiTakeover` runs the game as normal

Navigating to /home/(user)/doki in the terminal and running `Doki.Doki.Takeover.Linux/DokiTakeover` results in the error:
[Error : Could not load module lime@lime_application_create__prime]

Navigating to /home/(user)/doki in the terminal and running `./Doki.Doki.Takeover.Linux/DokiTakeover` results in the error:
[Error : Could not load module lime@lime_application_create__prime]

Navigating to any other directory and providing a file path to execute [DokiTakeover] results in the error:
[Error : Could not load module lime@lime_application_create__prime]

**Comment by EndEmpire** [comment]
I would like to humbly request that this issue be reconsidered based on my second post @ActualMandM

**Comment by ActualMandM** [comment]
It sounds like an issue related to [Lime](https://github.com/openfl/lime) itself, which means there's nothing that we can really do on the FNF side of things.
