### ISSUE TITLE
I downloaded the file, extracted it with 7zip, and it keeps showing this error every time I open the game Paths.hx (line 288) FirstBootState.hx (line 33) flixel/FlxGame.hx (line 642) flixel/FlxGame.hx (line 729) flixel/FlxGame.hx (line 682) flixel/FlxGame.hx (line 556) openfl/events/EventDispatcher.hx (line 402) openfl/display/DisplayObject.hx (line 1399)  Uncaught Error: Null Object Reference

### ISSUE THREAD

**Issue by Debalical360** [Jorge-SunSpirit/Doki-Doki-Takeover#18]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by Debalical360** [comment]
Paths.hx (line 288)
FirstBootState.hx (line 33)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

**Comment by ActualMandM** [comment]
Can you try this and see if it fixes the crash?
[DokiTakeover.zip](https://github.com/Jorge-SunSpirit/Doki-Doki-Takeover/files/10951931/DokiTakeover.zip)

**Comment by Debalical360** [comment]
It fixed it, thanks!

**Comment by Debalical360** [comment]
Sorry to bother again, I was playing the mod and after I got through Bara No Yume, I got another crash.
hxcodec/vlc/VLCBitmap.hx (line 367)
hxcodec/vlc/VLCBitmap.hx (line 300)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

**Comment by ActualMandM** [comment]
Not sure if that's possible to fix, since that's related to video playback. What are your computer specs?

**Comment by Debalical360** [comment]
How exactly would I go about finding that?

**Comment by ActualMandM** [comment]
The performance tab in Task Manager can show your specs. The most important ones are what CPU, Memory, and GPU say.

**Comment by Debalical360** [comment]
The base speed for CPU is 2.55 GHz, for memory base speed is 2133 MHz, and GPU memory is 0.2 GB.

**Comment by ActualMandM** [comment]
What does it say in the top right of each?
![2023-03-12_15-24-56_Taskmgr](https://user-images.githubusercontent.com/15317421/224577488-eabbca58-77fd-4869-8dbe-e2df3bcaf978.png)

**Comment by Debalical360** [comment]
This is what you're talking about, right?
![Screenshot 2023-03-12 190846](https://user-images.githubusercontent.com/127692179/224579677-fd76dcdf-2dba-4a30-b053-a1b92d82bae3.png)

**Comment by Debalical360** [comment]
Wait top right hold on

**Comment by Debalical360** [comment]
![Screenshot 2023-03-12 191527](https://user-images.githubusercontent.com/127692179/224580007-950b10b0-8f30-419c-994e-1c86c92de258.png)
![Screenshot 2023-03-12 191540](https://user-images.githubusercontent.com/127692179/224580008-e8ebb17a-365f-4e89-bb17-ce3cb782fb82.png)
![Screenshot 2023-03-12 191555](https://user-images.githubusercontent.com/127692179/224580009-ae4e01aa-d38f-458b-bd9a-9d97dd3b0b30.png)

**Comment by ActualMandM** [comment]
Unfortunately I don't think there's anything we can do about this issue... Your best bet is to wait for someone to port the mod's update to HTML5 or to Android.
