### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by Lila-Rogers** [Jorge-SunSpirit/Doki-Doki-Takeover#19]
Apparently there are several memory leaks in the weeks after Monika and in some other songs like Epiphany (this one was playable even with the lag) but I couldn't test it because the Hot Air Ballon was unplayable it was so lagged, sorry for seeing the bag with that but I don't have what it takes to get a new pc...

**Comment by ActualMandM** [comment]
Hello! Can you try toggling off GPU Textures in v3.0.1 and seeing if it helps with the performance?

**Comment by ActualMandM** [comment]
Last thing I can figure is trying to see if disabling shaders helps out at all in this situation.

**Comment by Lila-Rogers** [comment]
> Last thing I can figure is trying to see if disabling shaders helps out at all in this situation.

I had already tried disabling the shaders, but it didn't affect anything either, so apparently there's no solution, sorry for bothering the team with this

**Comment by ActualMandM** [comment]
I just realized a very dumb mistake I made, can you try this executable? The password of the 7z inside is set to `doki` because of Windows Defender.

[DokiTakeover.zip](https://github.com/Jorge-SunSpirit/Doki-Doki-Takeover/files/10963537/DokiTakeover.zip)
