### ISSUE TITLE
How to Compile The Source

### ISSUE THREAD

**Issue by AtlasGamer27** [Jorge-SunSpirit/Doki-Doki-Takeover#20]
I am very well versed in coding (yes ik that sounds stupid here since I am opening an issue), but right now I am trying to compile the source code, and every time i do it returns

`source/PlayState.hx:77: characters 8-28 : Type not found : hxcodec.VideoHandler`
`source/PlayState.hx:78: characters 8-27 : Type not found : hxcodec.VideoSprite`
`source/PlayState.hx:369: characters 16-27 : Type not found : VideoSprite`
`source/Debug.hx:20: lines 20-424 : ... Defined in this class`
`source/PlayState.hx:102: characters 2-47 : Method set_songSpeed required by property songSpeed is missing `
`source/DokiStoryState.hx:32: characters 8-28 : Type not found : hxcodec.VideoHandler`
`source/MainMenuState.hx:257: characters 17-20 : Cannot access static field add from a class instance`
`source/Character.hx:104: characters 13-23 : Class<PlayState> has no field altSection`
`source/DokiFreeplayState.hx:257: characters 17-20 : Cannot access static field add from a class instance  `
`source/DokiFreeplayState.hx:282: characters 17-20 : Cannot access static field add from a class instance  `
`source/DokiFreeplayState.hx:292: characters 16-19 : Cannot access static field add from a class instance  `
`source/DokiFreeplayState.hx:304: characters 16-19 : Cannot access static field add from a class instance  `
`source/DokiModifierSubState.hx:70: characters 17-20 : Cannot access static field add from a class instance`
`source/DokiStoryState.hx:198: characters 18-21 : Cannot access static field add from a class instance     `
`source/DokiStoryState.hx:556: characters 18-21 : Cannot access static field add from a class instance     `
`source/DokiStoryState.hx:363: characters 13-26 : Class<PlayState> has no field campaignScore`
`source/Note.hx:248: characters 46-57 : Class<PlayState> has no field daPixelZoom`
`source/Note.hx:255: characters 70-81 : Class<PlayState> has no field daPixelZoom`
`source/Note.hx:179: characters 26-37 : Class<PlayState> has no field daPixelZoom`
`source/ChartingState.hx:892: characters 21-26 : flixel.system.FlxSound has no field pitch`
`source/ChartingState.hx:898: characters 11-16 : flixel.system.FlxSound has no field pitch`
`source/ChartingState.hx:1042: characters 15-27 : Class<PlayState> has no field sectionStart`
`source/ChartingState.hx:1070: characters 15-27 : Class<PlayState> has no field sectionStart`
`source/ChartingState.hx:1085: characters 16-28 : Class<PlayState> has no field sectionStart`
`source/ChartingState.hx:1087: characters 16-33 : Class<PlayState> has no field sectionStartPoint`
`source/ChartingState.hx:1088: characters 16-32 : Class<PlayState> has no field sectionStartTime`
`source/flixel/addons/display/FlxBackdrop.hx:94: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:142: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:150: characters 18-19 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:151: characters 18-19 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:413: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:419: characters 21-22 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:420: characters 21-22 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:423: characters 21-22 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:424: characters 21-22 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:426: characters 21-22 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:427: characters 21-22 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:429: characters 21-22 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:429: characters 44-45 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:430: characters 21-22 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:430: characters 44-45 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:450: characters 20-21 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:456: characters 20-21 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:493: characters 30-31 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:494: characters 30-31 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:191: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:209: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:212: characters 19-20 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:221: characters 19-20 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:262: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:312: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:316: characters 19-20 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:325: characters 19-20 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:182: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/DialogueBox.hx:885: characters 72-83 : Class<PlayState> has no field daPixelZoom`
`source/DialogueBox.hx:894: characters 74-85 : Class<PlayState> has no field daPixelZoom`
`source/DialogueBox.hx:903: characters 54-65 : Class<PlayState> has no field daPixelZoom`
`source/DialogueBox.hx:272: characters 22-37 : PlayState has no field cleanupCutscene`
`source/DialogueBox.hx:683: characters 24-40 : PlayState has no field playbackCutscene`
`source/DialogueBox.hx:225: characters 22-37 : PlayState has no field cleanupCutscene`
`source/StrumNote.hx:66: characters 46-57 : Class<PlayState> has no field daPixelZoom`
`source/Character.hx:311: characters 35-45 : Class<PlayState> has no field altSection`

Yes I know its a lot, I think I am missing some packages but I am not sure which ones...

**Comment by ActualMandM** [comment]
Have you tried installing hxCodec? The BUILDING.md file mentions it.

**Comment by AtlasGamer27** [comment]
Oh... I am very small brain... maybe I should have read that XD

But now I am getting brand new errors, different ones
`source/MainMenuState.hx:257: characters 17-20 : Cannot access static field add from a class instance`
`source/DokiFreeplayState.hx:257: characters 17-20 : Cannot access static field add from a class instance`       
`source/DokiFreeplayState.hx:282: characters 17-20 : Cannot access static field add from a class instance `      
`source/DokiFreeplayState.hx:292: characters 16-19 : Cannot access static field add from a class instance  `     
`source/DokiFreeplayState.hx:304: characters 16-19 : Cannot access static field add from a class instance   `    
`source/DokiModifierSubState.hx:70: characters 17-20 : Cannot access static field add from a class instance`     
`source/DokiStoryState.hx:198: characters 18-21 : Cannot access static field add from a class instance`
`source/DokiStoryState.hx:556: characters 18-21 : Cannot access static field add from a class instance`
`source/ChartingState.hx:892: characters 21-26 : flixel.system.FlxSound has no field pitch`
`source/ChartingState.hx:898: characters 11-16 : flixel.system.FlxSound has no field pitch`
`source/flixel/addons/display/FlxBackdrop.hx:94: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes `
`source/flixel/addons/display/FlxBackdrop.hx:142: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:150: characters 18-19 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:151: characters 18-19 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:413: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:419: characters 21-22 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:420: characters 21-22 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:423: characters 21-22 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:424: characters 21-22 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:426: characters 21-22 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:427: characters 21-22 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:429: characters 21-22 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:429: characters 44-45 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:430: characters 21-22 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:430: characters 44-45 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:450: characters 20-21 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:456: characters 20-21 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:493: characters 30-31 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:494: characters 30-31 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:191: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:209: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:212: characters 19-20 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:221: characters 19-20 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:262: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:312: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/flixel/addons/display/FlxBackdrop.hx:316: characters 19-20 : flixel.util.FlxAxes has no field x`
`source/flixel/addons/display/FlxBackdrop.hx:325: characters 19-20 : flixel.util.FlxAxes has no field y`
`source/flixel/addons/display/FlxBackdrop.hx:182: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes`
`source/PlayState.hx:3630: characters 20-25 : flixel.system.FlxSound has no field pitch`
`source/PlayState.hx:3634: characters 10-15 : flixel.system.FlxSound has no field pitch`
`source/PlayState.hx:4391: characters 20-25 : flixel.system.FlxSound has no field pitch`
`source/PlayState.hx:4398: characters 10-15 : flixel.system.FlxSound has no field pitch`
`source/PlayState.hx:4473: characters 20-25 : flixel.system.FlxSound has no field pitch`
`source/PlayState.hx:4476: characters 11-16 : flixel.system.FlxSound has no field pitch`

Now I am really confused

**Comment by ActualMandM** [comment]
You need to update HaxeFlixel. We make use of 5.0.0 features in this mod

**Comment by AtlasGamer27** [comment]
Cool! It compiled.. just to let you know lime and HaxeFlixel wasn't updated so I had to update them. And for anyone with Psych Engine knowledge you need to update hxCodec as well to the latest version
