### ISSUE TITLE
[QUESTION] Localization system

### ISSUE THREAD

**Issue by AltronMaxX** [Jorge-SunSpirit/Doki-Doki-Takeover#21]
After studying the mod code, I found out that the localization system is ready and works well, except for dialogs, what was the reason for its removal? And also, if I restore the localization system and add dialog localization, will it be loaded into the mod code? And the last, I with my friend will work with Russian localization.

**Comment by AltronMaxX** [comment]
Well, I've done something with localized dialogues in my fork of the mod. Maybe it can help you :)

**Comment by ActualMandM** [comment]
The latest version is fully set up for localization, however v3.0.4 is gonna be the final update to the mod as we want to move on to other projects.

You can make a fork with your translation though.
