### ISSUE TITLE
When i open epinhany song this happen:

### ISSUE THREAD

**Issue by taleslins** [Jorge-SunSpirit/Doki-Doki-Takeover#22]
![Monika Epiphany song](https://user-images.githubusercontent.com/64812534/224842925-c50bd5fb-de53-4527-972f-003c5b67f13b.PNG)
I can't play epiphany song for some reason.

**Comment by ActualMandM** [comment]
Can you try this executable and see if it fixes the issue?
[DokiTakeover.zip](https://github.com/Jorge-SunSpirit/Doki-Doki-Takeover/files/10962393/DokiTakeover.zip)

**Comment by Danmccool** [comment]
hey ActualMandM that has a virus in it so take it down

**Comment by taleslins** [comment]
YEAH!! it worked, thanks!!

**Comment by ActualMandM** [comment]
> hey ActualMandM that has a virus in it so take it down

It's Windows Defender being stupid...

**Comment by Danmccool** [comment]
are you sure

**Comment by ActualMandM** [comment]
yes

**Comment by Danmccool** [comment]
ok
