### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Bruhwhatthefuc** [Jorge-SunSpirit/Doki-Doki-Takeover#24]
weird bug but sayori isn't in the bg when i play any song through freeplay, also the exit game options are swapped

**Comment by Bruhwhatthefuc** [comment]
weird bug but sayori isn't in the bg when i play any song through freeplay, also the exit game options are swapped

**Comment by ActualMandM** [comment]
Are you using any costumes in Freeplay? Also the exit game option starts on No in case you mis-clicked onto the option.

**Comment by Bruhwhatthefuc** [comment]
no, i still haven't even unlocked them, and i thought i should say yes because it was asking me if i'm sure or not but it only exit when i say no

**Comment by Bruhwhatthefuc** [comment]
okay so sayori is now back in the bg after i unlocked the costumes, weird
