### ISSUE TITLE
Alternate download besides Google Drive? 

### ISSUE THREAD

**Issue by RowanSkie** [Jorge-SunSpirit/Doki-Doki-Takeover#25]
Hi, I've been trying to download this mod. It's kinda hard to download when Github cuts the download close to the end and Google Drive decided that it's quota'd.

**Comment by ActualMandM** [comment]
Here's a MediaFire rehost: https://www.mediafire.com/file/sugpuh9b0qgq69t/DDTO%252B_v3.0.3.7z/file
