### ISSUE TITLE
I cannot compile.

### ISSUE THREAD

**Issue by jmxamongusmodder** [Jorge-SunSpirit/Doki-Doki-Takeover#26]
Alright so its just missing almost everything and i have everything i need downloaded.
It wants stuff that isnt in the code.
WHY.
Fix this.

**Comment by ActualMandM** [comment]
Please follow [BUILDING.md](https://github.com/Jorge-SunSpirit/Doki-Doki-Takeover/blob/main/BUILDING.md) in regards to how to build. I've just noted the versions required, in order to reduce confusion.
