### ISSUE TITLE
Bug Report: When i enter the last week, this error show up, i think it might be a stage thing or whatever

### ISSUE THREAD

**Issue by TheJustAnto** [Jorge-SunSpirit/Doki-Doki-Takeover#27]
[####](url) Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## Please describe your issue. Provide extensive detail and images if possible.
![image](https://user-images.githubusercontent.com/125211085/225353372-25e3d22e-e2a1-4ef1-ab02-0f4941b7a325.png)

**Comment by ActualMandM** [comment]
Which week? Protag or Side Stories

**Comment by TheJustAnto** [comment]
> 

potagonist week

**Comment by ActualMandM** [comment]
Sounds like the install might be bad. Have you tried redownloading?

**Comment by TheJustAnto** [comment]
Oh yeah but it was just 1 crash and it was good after that didn't needed to reinstall it

**Comment by ActualMandM** [comment]
Wait, so it only crashed that one time?

**Comment by ActualMandM** [comment]
I've made it so v3.0.3 brings up a popup in case a scenario like this happens.
