### ISSUE TITLE
Bug Report: thanks for fixing fps drop in encore week, appreciate your effort!! love n' funkin still has fps drop - is there any way to fix it? sorry for bothering-

### ISSUE THREAD

**Issue by Shou-chan1487** [Jorge-SunSpirit/Doki-Doki-Takeover#28]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by Shou-chan1487** [comment]
ohh okay! thank you so much for the attetion and the mod!! <33

**Comment by ActualMandM** [comment]
Fixed with v3.0.3.
https://github.com/Jorge-SunSpirit/Doki-Doki-Takeover/releases/tag/v3.0.3
