### ISSUE TITLE
Bug Report: I'm not sure if this is a bug or a coincidence, but every time I open the mod, only monika appears in the intro (none of the other dokis appeared since the new update) and as soon as we press enter to go to the main menu, yuri also always appears, after a few returns to the menu it goes back to normal  I tested it on the first release version and it doesn't, sorry for the inconvenience again-  also thanks a lot for the low end mode! >w<

### ISSUE THREAD

**Issue by Shou-chan1487** [Jorge-SunSpirit/Doki-Doki-Takeover#32]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by ActualMandM** [comment]
This issue has already been fixed (53bf5c246694523f8c25733479425c5d8444c957) and will be in the next update.

For now, you can use this executable. The password is `doki`.
[DokiTakeover.zip](https://github.com/Jorge-SunSpirit/Doki-Doki-Takeover/files/11011742/DokiTakeover.zip)

**Comment by Shou-chan1487** [comment]
Oh okay!! thank you again!! <33
