### ISSUE TITLE
Bug Report: Asset Sound Error

### ISSUE THREAD

**Issue by KodyKodster** [Jorge-SunSpirit/Doki-Doki-Takeover#36]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows x64

## What version of the game are you using? Look in the bottom left corner of the main menu.
V 3.1.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Just beat "Your Demise" from Game 1
## Please describe your issue. Provide extensive detail and images if possible.
There seems to be a sound unable to be loaded, that causes the game to crash and bars you from continuing further in the act. Crash report is below:

openfl/media/Sound.hx (line 407)
Paths.hx (line 373)
Paths.hx (line 202)
PlayState.hx (line 3067)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Error loading sound from file: ./assets/sounds/dah.ogg
Please report this error to the GitHub page: https://github.com/Jorge-SunSpirit/Doki-Doki-Takeover

**Comment by AtlasGamer27** [comment]
If you DM me on discord, I can give you a non crashing one, I figured out the issue

**Comment by ActualMandM** [comment]
Fixed with #38, will be pushing an update in a bit.

**Comment by RagdollClash** [comment]
v3.1.2 is up with the fix!
https://github.com/Jorge-SunSpirit/Doki-Doki-Takeover/releases/tag/v3.1.2
