### ISSUE TITLE
Bug Report: scores not saving

### ISSUE THREAD

**Issue by Amazingpotato917** [Jorge-SunSpirit/Doki-Doki-Takeover#39]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below. 
Windows, not sure which one-

## What version of the game are you using? Look in the bottom left corner of the main menu.
3.1.1 I think it's called, it's the new one

## Please describe your issue. Provide extensive detail and images if possible.
So I play the new songs and none of my scores have saved, they all stay at 0, just for the new songs

**Comment by ActualMandM** [comment]
Fixed with #40, will be in the upcoming update.

**Comment by RagdollClash** [comment]
v3.1.2 is up with the fix!
https://github.com/Jorge-SunSpirit/Doki-Doki-Takeover/releases/tag/v3.1.2
