### ISSUE TITLE
Enhancement: i wanna give you the mac version 

### ISSUE THREAD

**Issue by ghost** [Jorge-SunSpirit/Doki-Doki-Takeover#5]
how dare you not have the mac version

**Comment by SpaceCheeseWizard** [comment]
I too would like a mac version please. I'd even pay you for your time.

**Comment by ActualMandM** [comment]
We don't have anyone who can compile the mod for Mac, as it requires you to be on an actual Mac

**Comment by SpaceCheeseWizard** [comment]
Thank you for the fast reply. If I learn how to compile Mods, I will reach back to you.

**Comment by Jonnycatmeow** [comment]
let me compile it for macos

**Comment by fixmyblock** [comment]
I compiled the macOS (x64) version, I bundled it in a .DMG so, can I upload it here?
